package goldmark_test

import (
	"bytes"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/yuin/goldmark/v2/ast"
	"github.com/yuin/goldmark/v2/parser"
	"github.com/yuin/goldmark/v2/renderer/html"
	"github.com/yuin/goldmark/v2/testutil"
)

var testTimeoutMultiplier = 1.0

func init() {
	m, err := strconv.ParseFloat(os.Getenv("GOLDMARK_TEST_TIMEOUT_MULTIPLIER"), 64)
	if err == nil {
		testTimeoutMultiplier = m
	}
}

func TestExtras(t *testing.T) {
	markdown := testutil.NewMarkdownToStringFunc(
		parser.New(),
		html.New(html.WithXHTML(), html.WithUnsafe()),
	)
	testutil.DoTestCaseFile(markdown, "_test/extra.txt", t, testutil.ParseCliCaseArg()...)
}

func TestEndsWithNonSpaceCharacters(t *testing.T) {
	p := parser.New()
	r := html.New(html.WithXHTML(), html.WithUnsafe())
	source := []byte("```\na\n```")
	var b bytes.Buffer
	err := r.Render(&b, source, p.Parse(source))
	if err != nil {
		t.Error(err.Error())
	}
	if b.String() != "<pre><code>a\n</code></pre>\n" {
		t.Errorf("%s \n---------\n %s", source, b.String())
	}
}

func TestWindowsNewLine(t *testing.T) {
	p := parser.New()
	r := html.New(html.WithXHTML())
	source := []byte("a  \r\nb\n")
	var b bytes.Buffer
	err := r.Render(&b, source, p.Parse(source))
	if err != nil {
		t.Error(err.Error())
	}
	if b.String() != "<p>a<br />\nb</p>\n" {
		t.Errorf("%s\n---------\n%s", source, b.String())
	}

	source = []byte("a\\\r\nb\r\n")
	var b2 bytes.Buffer
	err = r.Render(&b2, source, p.Parse(source))
	if err != nil {
		t.Error(err.Error())
	}
	if b2.String() != "<p>a<br />\nb</p>\n" {
		t.Errorf("\n%s\n---------\n%s", source, b2.String())
	}
}

type myIDGenerator struct {
}

func (s *myIDGenerator) Generate(_ []byte, _ ast.NodeKind) []byte {
	return []byte("my-id")
}

func TestAutogeneratedIDs(t *testing.T) {
	p := parser.New(parser.WithAutoHeadingID(), parser.WithIDGenerator(&myIDGenerator{}))
	r := html.New()

	source := []byte("# Title1\n## Title2")
	var b bytes.Buffer
	err := r.Render(&b, source, p.Parse(source))
	if err != nil {
		t.Error(err.Error())
	}
	if b.String() != `<h1 id="my-id">Title1</h1>
<h2 id="my-id-1">Title2</h2>
` {
		t.Errorf("%s\n---------\n%s", source, b.String())
	}
}

func nowMillis() int64 {
	// TODO: replace UnixNano to UnixMillis(drops Go1.16 support)
	return time.Now().UnixNano() / 1000000
}

func TestDeepNestedLabelPerformance(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping performance test in short mode")
	}
	p := parser.New()
	r := html.New(html.WithXHTML(), html.WithUnsafe())

	started := nowMillis()
	n := 50000
	source := []byte(strings.Repeat("[", n) + strings.Repeat("]", n))
	var b bytes.Buffer
	_ = r.Render(&b, source, p.Parse(source))
	finished := nowMillis()
	if (finished - started) > int64(5000*testTimeoutMultiplier) {
		t.Error("Parsing deep nested labels took too long")
	}
}

func TestManyProcessingInstructionPerformance(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping performance test in short mode")
	}
	p := parser.New()
	r := html.New(html.WithXHTML(), html.WithUnsafe())

	started := nowMillis()
	n := 50000
	source := []byte("a " + strings.Repeat("<?", n))
	var b bytes.Buffer
	_ = r.Render(&b, source, p.Parse(source))
	finished := nowMillis()
	if (finished - started) > int64(5000*testTimeoutMultiplier) {
		t.Error("Parsing processing instructions took too long")
	}
}

func TestManyCDATAPerformance(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping performance test in short mode")
	}
	p := parser.New()
	r := html.New(html.WithXHTML(), html.WithUnsafe())

	started := nowMillis()
	n := 50000
	source := []byte(strings.Repeat("a <![CDATA[", n))
	var b bytes.Buffer
	_ = r.Render(&b, source, p.Parse(source))
	finished := nowMillis()
	if (finished - started) > int64(5000*testTimeoutMultiplier) {
		t.Error("Parsing processing instructions took too long")
	}
}

func TestManyDeclPerformance(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping performance test in short mode")
	}
	p := parser.New()
	r := html.New(html.WithXHTML(), html.WithUnsafe())

	started := nowMillis()
	n := 50000
	source := []byte(strings.Repeat("a <!A ", n))
	var b bytes.Buffer
	_ = r.Render(&b, source, p.Parse(source))
	finished := nowMillis()
	if (finished - started) > int64(5000*testTimeoutMultiplier) {
		t.Error("Parsing processing instructions took too long")
	}
}

func TestManyCommentPerformance(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping performance test in short mode")
	}
	p := parser.New()
	r := html.New(html.WithXHTML(), html.WithUnsafe())

	started := nowMillis()
	n := 50000
	source := []byte(strings.Repeat("a <!-- ", n))
	var b bytes.Buffer
	_ = r.Render(&b, source, p.Parse(source))
	finished := nowMillis()
	if (finished - started) > int64(5000*testTimeoutMultiplier) {
		t.Error("Parsing processing instructions took too long")
	}
}

func TestDangerousURLStringCase(t *testing.T) {
	p := parser.New()
	r := html.New()
	source := []byte(`[Basic](javascript:alert('Basic'))
[CaseInsensitive](JaVaScRiPt:alert('CaseInsensitive'))
`)
	expected := []byte(`<p><a href="">Basic</a>
<a href="">CaseInsensitive</a></p>
`)
	var b bytes.Buffer
	_ = r.Render(&b, source, p.Parse(source))
	if !bytes.Equal(expected, b.Bytes()) {
		t.Error("Dangerous URL should ignore cases:\n" + string(testutil.DiffPretty(expected, b.Bytes())))
	}
}

func TestATXHeadingAttributes(t *testing.T) {
	p := parser.New(parser.WithAutoHeadingID(), parser.WithAttribute())

	source := []byte(`# Heading {#my-id .my-class custom="hello"}`)
	n := p.Parse(source)
	heading := n.FirstChild()
	if heading.Kind() != ast.KindHeading {
		t.Fatalf("expected first node to be heading, got %s", heading.Kind().String())
	}
	idVal, ok := heading.Attribute("id")
	if !ok {
		t.Fatal("expected to find attribute 'id'")
	}
	if string(idVal.Bytes(nil)) != "my-id" {
		t.Fatalf("expected id 'my-id', got %s", string(idVal.Bytes(nil)))
	}
	customVal, ok := heading.Attribute("custom")
	if !ok {
		t.Fatal("expected to find attribute 'custom'")
	}
	if string(customVal.Bytes(nil)) != "hello" {
		t.Fatalf("expected custom 'hello', got %s", string(customVal.Bytes(nil)))
	}
}

func TestDangerousURLWithReferences(t *testing.T) {
	p := parser.New(parser.WithAutoHeadingID(), parser.WithAttribute())
	r := html.New()

	source := []byte(`[click](&#106;avascript:alert(1))`)
	expected := []byte(`<p><a href="">click</a></p>
`)
	var b bytes.Buffer
	_ = r.Render(&b, source, p.Parse(source))
	if !bytes.Equal(expected, b.Bytes()) {
		t.Error("Dangerous URL with references should not be rendered:\n" + string(testutil.DiffPretty(expected, b.Bytes())))
	}

	source = []byte(`<javascript:alert(document.domain)>`)
	expected = []byte(`<p><a href="">javascript:alert(document.domain)</a></p>
`)
	b.Reset()
	_ = r.Render(&b, source, p.Parse(source))
	if !bytes.Equal(expected, b.Bytes()) {
		t.Error("Dangerous autolink should not be rendered:\n" + string(testutil.DiffPretty(expected, b.Bytes())))
	}

	source = []byte(`![alt](javascript:alert(document.domain))`)
	expected = []byte(`<p><img src="" alt="alt"></p>
`)
	b.Reset()
	_ = r.Render(&b, source, p.Parse(source))
	if !bytes.Equal(expected, b.Bytes()) {
		t.Error("Dangerous image should not be rendered:\n" + string(testutil.DiffPretty(expected, b.Bytes())))
	}
}
